-- Create SQLite tables

-- 2. Construa uma query SQL para criar a tabela CUSTOMERS (Clientes) no banco de dados.
CREATE TABLE IF NOT EXISTS CUSTOMERS (
  ID         INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME       VARCHAR(128) NOT NULL,
  LASTNAME   VARCHAR(155) NOT NULL,
  PHONE      VARCHAR(16) NOT NULL,
  EMAIL      VARCHAR(32) NOT NULL,
  ADDRESS    VARCHAR(200) NOT NULL,
  CITY       VARCHAR(64) NOT NULL,
  STATE      VARCHAR(2) NOT NULL,
  BIRTH_DATE DATETIME NOT NULL
);

-- 3. Construa uma query SQL para criar a tabela CAR_MODELS (modelos) no banco de dados.
CREATE TABLE IF NOT EXISTS CAR_MODELS (
  ID         INTEGER PRIMARY KEY AUTOINCREMENT,
  MODEL_NAME VARCHAR(120) NOT NULL
);

-- 4. Construa uma query SQL para criar a tabela CAR_BRANDS (marcas) no banco de dados.
CREATE TABLE IF NOT EXISTS CAR_BRANDS (
  ID         INTEGER PRIMARY KEY AUTOINCREMENT,
  BRAND_NAME VARCHAR(32) NOT NULL
);

-- 5. Construa uma query SQL para criar a tabela POSITIONS (Cargos) no banco de dados.
CREATE TABLE IF NOT EXISTS POSITIONS (
  ID          INTEGER PRIMARY KEY AUTOINCREMENT,
  DESCRIPTION VARCHAR(120) NOT NULL
);

-- 6. Construa uma query SQL para criar a tabela EMPLOYEES (Funcionários) no banco de dados.
CREATE TABLE IF NOT EXISTS EMPLOYEES (
  ID            INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME          VARCHAR(100) NOT NULL,
  PHONE         VARCHAR(16) NOT NULL,
  CONTRACT_DATE DATETIME NOT NULL,
  POSITION_ID   INTEGER NOT NULL,

  FOREIGN KEY(POSITION_ID) REFERENCES POSITIONS(ID)
);

-- 7. Construa uma query SQL para criar a tabela CARS (Carros) no banco de dados.
CREATE TABLE IF NOT EXISTS CARS (
  ID         INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME       VARCHAR(120) NOT NULL,
  YEAR       INTEGER NOT NULL,
  COLOR      VARCHAR(32) NOT NULL,
  KM         FLOAT(10,2) NOT NULL,
  STATUS     VARCHAR(17) NOT NULL,
  BRAND_ID   INTEGER NOT NULL,
  MODEL_ID   INTEGER NOT NULL,

  FOREIGN KEY(BRAND_ID) REFERENCES CAR_BRANDS(ID),
  FOREIGN KEY(MODEL_ID) REFERENCES CAR_MODELS(ID)
);

-- 8. Construa uma query SQL para criar a tabela LOCATIONS (Locações) no banco de dados.
CREATE TABLE IF NOT EXISTS LOCATIONS (
  ID INTEGER  PRIMARY KEY AUTOINCREMENT,
  START_DATE  DATETIME NOT NULL,
  END_DATE    DATETIME NOT NULL,
  TOTAL       FLOAT(10,2) NOT NULL,
  CUSTOMER_ID INTEGER NOT NULL,
  CAR_ID      INTEGER NOT NULL,
  EMPLOYEE_ID INTEGER NOT NULL,

  FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
  FOREIGN KEY(CAR_ID) REFERENCES CARS(ID),
  FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
);
