-- Create SQLite tables

DROP TABLE IF EXISTS LOCATIONS;

-- People related tables

DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS EMPLOYEES;
DROP TABLE IF EXISTS POSITIONS;

-- Cars related tables

DROP TABLE IF EXISTS CARS;
DROP TABLE IF EXISTS CAR_BRANDS;
DROP TABLE IF EXISTS CAR_MODELS;

